# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180509_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='login_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles//%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
